### ISSUE TITLE
Textures doesn't render properly after opening a new project and addidng material component

### ISSUE THREAD

**Issue by mdoradom** [Brewing-Team/Coffee-Engine#37]
**Describe the bug**
When you open a existing project, and add a material component after, the textures doesn't render at all.

**To Reproduce**
1. Open a project
2. Add material component to a object
3. Add a texture to the object

**Expected behavior**
Render the debug and selected textures normaly

**Screenshots**
![image](https://github.com/user-attachments/assets/3425fa02-f2ef-45ca-8241-fb0203dae5e2)

**Comment by HugoPlacer** [comment]
I tried with the plane primitive and it does not happen.

The code to spawn the plane ( Scene.cpp OnInit() ):
```cpp
        Entity primitive = CreateEntity("Primitive");
        const Ref<Mesh>& planeMesh = PrimitiveMesh::CreatePlane({1.0f, 1.0f});
        primitive.AddComponent<MeshComponent>(planeMesh);
```

The result after adding a Material Component and assigning a image from the content browser:
![Captura de pantalla_20241004_194602](https://github.com/user-attachments/assets/20c47b39-a312-4bb1-8118-b5b269a27e54)

**Comment by HugoPlacer** [comment]
While with the plane has worked, with the other primitives I haven't been so lucky. I confirm that something happen with the material when a project is loaded.

![Captura de pantalla_20241005_155216](https://github.com/user-attachments/assets/cfb9f907-bb90-4320-b780-397d1d332b8e)
