### ISSUE TITLE
Building the Engine in Release mode on Windows crash

### ISSUE THREAD

**Issue by HugoPlacer** [Brewing-Team/Coffee-Engine#51]
**Describe the bug**
When building on Windows spdlog mutex lock crash.

https://github.com/gabime/spdlog/issues/2267

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mdoradom** [comment]
Probably related to https://github.com/gabime/spdlog/issues/1505

**Comment by HugoPlacer** [comment]
Probably related to https://github.com/gabime/spdlog/issues/3145

**Comment by HugoPlacer** [comment]
I can't reproduce the issue at the home pc

**Comment by mdoradom** [comment]
The problem is that the VS cpp runtime version installed in our class system, is outdated and doesn't have the fix for the mutex conflict. The fix is to have the latest VS version.
